///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("14e8a3c3-07a5-4ee7-a9da-14d50d2d9f34")]
    public partial class DemoRepository : RepoGenBaseFolder
    {
        static DemoRepository instance = new DemoRepository();
        DemoRepositoryFolders.FormVipApplicationAppFolder _formvipapplication;

        /// <summary>
        /// Gets the singleton class instance representing the DemoRepository element repository.
        /// </summary>
        [RepositoryFolder("14e8a3c3-07a5-4ee7-a9da-14d50d2d9f34")]
        public static DemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DemoRepository() 
            : base("DemoRepository", "/", null, 0, false, "14e8a3c3-07a5-4ee7-a9da-14d50d2d9f34", ".\\RepositoryImages\\DemoRepository14e8a3c3.rximgres")
        {
            _formvipapplication = new DemoRepositoryFolders.FormVipApplicationAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("14e8a3c3-07a5-4ee7-a9da-14d50d2d9f34")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FormVipApplication folder.
        /// </summary>
        [RepositoryFolder("909831ae-d73d-4fcb-808a-82d9c961a40c")]
        public virtual DemoRepositoryFolders.FormVipApplicationAppFolder FormVipApplication
        {
            get { return _formvipapplication; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class DemoRepositoryFolders
    {
        /// <summary>
        /// The FormVipApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("909831ae-d73d-4fcb-808a-82d9c961a40c")]
        public partial class FormVipApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _movieInfo;
            RepoItemInfo _rbmaleInfo;
            RepoItemInfo _btaddInfo;
            RepoItemInfo _firstnamerow0Info;
            RepoItemInfo _btclearInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _musicInfo;

            /// <summary>
            /// Creates a new FormVipApplication  folder.
            /// </summary>
            public FormVipApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormVipApplication", "/form[@controlname='formVipApplication']", parentFolder, 30000, null, true, "909831ae-d73d-4fcb-808a-82d9c961a40c", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First Name:']", 30000, null, "ed34bdec-a1b9-4373-895e-fd5b01554ca1");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last Name:']", 30000, null, "f334b5d2-676e-4c6d-9fc7-e5629956ac5b");
                _movieInfo = new RepoItemInfo(this, "Movie", ".//listitem[@accessiblename='Movie']", 30000, null, "e2099f90-7eb4-4b97-8776-2b89e1038108");
                _rbmaleInfo = new RepoItemInfo(this, "RbMale", "?/?/radiobutton[@controlname='rbMale']", 30000, null, "8746acab-9aa8-41e8-bc74-709f48fcccb4");
                _btaddInfo = new RepoItemInfo(this, "BtAdd", "button[@controlname='btAdd']", 30000, null, "711993be-34cf-4b3f-82aa-ce586f624cb0");
                _firstnamerow0Info = new RepoItemInfo(this, "FirstNameRow0", ".//cell[@accessiblename='First Name Row 0']", 30000, null, "e59a942a-5c9d-4cc4-a7e4-195a24222ee0");
                _btclearInfo = new RepoItemInfo(this, "BtClear", "button[@controlname='btClear']", 30000, null, "2e74499f-3c34-4133-b79e-97ccce2f8da5");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "cf673b4e-854e-431e-9afc-dff3e03d1a76");
                _musicInfo = new RepoItemInfo(this, "Music", ".//listitem[@accessiblename='Music']", 30000, null, "5871bd91-9819-4fdc-82e7-70ceffbd3cec");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("909831ae-d73d-4fcb-808a-82d9c961a40c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("909831ae-d73d-4fcb-808a-82d9c961a40c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("ed34bdec-a1b9-4373-895e-fd5b01554ca1")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("ed34bdec-a1b9-4373-895e-fd5b01554ca1")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("f334b5d2-676e-4c6d-9fc7-e5629956ac5b")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("f334b5d2-676e-4c6d-9fc7-e5629956ac5b")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Movie item.
            /// </summary>
            [RepositoryItem("e2099f90-7eb4-4b97-8776-2b89e1038108")]
            public virtual Ranorex.ListItem Movie
            {
                get
                {
                    return _movieInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Movie item info.
            /// </summary>
            [RepositoryItemInfo("e2099f90-7eb4-4b97-8776-2b89e1038108")]
            public virtual RepoItemInfo MovieInfo
            {
                get
                {
                    return _movieInfo;
                }
            }

            /// <summary>
            /// The RbMale item.
            /// </summary>
            [RepositoryItem("8746acab-9aa8-41e8-bc74-709f48fcccb4")]
            public virtual Ranorex.RadioButton RbMale
            {
                get
                {
                    return _rbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RbMale item info.
            /// </summary>
            [RepositoryItemInfo("8746acab-9aa8-41e8-bc74-709f48fcccb4")]
            public virtual RepoItemInfo RbMaleInfo
            {
                get
                {
                    return _rbmaleInfo;
                }
            }

            /// <summary>
            /// The BtAdd item.
            /// </summary>
            [RepositoryItem("711993be-34cf-4b3f-82aa-ce586f624cb0")]
            public virtual Ranorex.Button BtAdd
            {
                get
                {
                    return _btaddInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtAdd item info.
            /// </summary>
            [RepositoryItemInfo("711993be-34cf-4b3f-82aa-ce586f624cb0")]
            public virtual RepoItemInfo BtAddInfo
            {
                get
                {
                    return _btaddInfo;
                }
            }

            /// <summary>
            /// The FirstNameRow0 item.
            /// </summary>
            [RepositoryItem("e59a942a-5c9d-4cc4-a7e4-195a24222ee0")]
            public virtual Ranorex.Cell FirstNameRow0
            {
                get
                {
                    return _firstnamerow0Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The FirstNameRow0 item info.
            /// </summary>
            [RepositoryItemInfo("e59a942a-5c9d-4cc4-a7e4-195a24222ee0")]
            public virtual RepoItemInfo FirstNameRow0Info
            {
                get
                {
                    return _firstnamerow0Info;
                }
            }

            /// <summary>
            /// The BtClear item.
            /// </summary>
            [RepositoryItem("2e74499f-3c34-4133-b79e-97ccce2f8da5")]
            public virtual Ranorex.Button BtClear
            {
                get
                {
                    return _btclearInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtClear item info.
            /// </summary>
            [RepositoryItemInfo("2e74499f-3c34-4133-b79e-97ccce2f8da5")]
            public virtual RepoItemInfo BtClearInfo
            {
                get
                {
                    return _btclearInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("cf673b4e-854e-431e-9afc-dff3e03d1a76")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("cf673b4e-854e-431e-9afc-dff3e03d1a76")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Music item.
            /// </summary>
            [RepositoryItem("5871bd91-9819-4fdc-82e7-70ceffbd3cec")]
            public virtual Ranorex.ListItem Music
            {
                get
                {
                    return _musicInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Music item info.
            /// </summary>
            [RepositoryItemInfo("5871bd91-9819-4fdc-82e7-70ceffbd3cec")]
            public virtual RepoItemInfo MusicInfo
            {
                get
                {
                    return _musicInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}