///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("d53d4761-a8ea-4e3b-b85c-c7fb03c69363", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DemoRepository repository.
        /// </summary>
        public static DemoRepository repo = DemoRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormVipApplication.FirstName' at 7;8.", repo.FormVipApplication.FirstNameInfo, new RecordItemIndex(0));
            repo.FormVipApplication.FirstName.Click("7;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Hermann' with focus on 'FormVipApplication.FirstName'.", repo.FormVipApplication.FirstNameInfo, new RecordItemIndex(1));
            repo.FormVipApplication.FirstName.PressKeys("Hermann");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormVipApplication.LastName' at 59;10.", repo.FormVipApplication.LastNameInfo, new RecordItemIndex(2));
            repo.FormVipApplication.LastName.Click("59;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Hafner' with focus on 'FormVipApplication.LastName'.", repo.FormVipApplication.LastNameInfo, new RecordItemIndex(3));
            repo.FormVipApplication.LastName.PressKeys("Hafner");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormVipApplication.Movie' at 32;3.", repo.FormVipApplication.MovieInfo, new RecordItemIndex(4));
            repo.FormVipApplication.Movie.Click("32;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormVipApplication.RbMale' at 7;8.", repo.FormVipApplication.RbMaleInfo, new RecordItemIndex(5));
            repo.FormVipApplication.RbMale.Click("7;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormVipApplication.BtAdd' at 32;10.", repo.FormVipApplication.BtAddInfo, new RecordItemIndex(6));
            repo.FormVipApplication.BtAdd.Click("32;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Hermann') on item 'FormVipApplication.FirstNameRow0'.", repo.FormVipApplication.FirstNameRow0Info, new RecordItemIndex(7));
            Validate.Attribute(repo.FormVipApplication.FirstNameRow0Info, "Text", "Hermann");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormVipApplication.BtClear' at 25;11.", repo.FormVipApplication.BtClearInfo, new RecordItemIndex(8));
            repo.FormVipApplication.BtClear.Click("25;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(null)') on item 'FormVipApplication.FirstNameRow0'.", repo.FormVipApplication.FirstNameRow0Info, new RecordItemIndex(9));
            Validate.Attribute(repo.FormVipApplication.FirstNameRow0Info, "Text", "(null)");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormVipApplication.Close' at 16;15.", repo.FormVipApplication.CloseInfo, new RecordItemIndex(10));
            repo.FormVipApplication.Close.Click("16;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeNotEqual (Text!='Audio') on item 'FormVipApplication.Music'.", repo.FormVipApplication.MusicInfo, new RecordItemIndex(11));
            Validate.AttributeNotEqual(repo.FormVipApplication.MusicInfo, "Text", "Audio");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
